CREATE TABLE FUTBOLISTA (futbolista_id SERIAL NOT NULL, documento_identidad varchar(20) NOT NULL UNIQUE, nombre_completo varchar(40) NOT NULL, nombre_corto varchar(15) NOT NULL, fecha_nacimiento date NOT NULL, altura float4 NOT NULL, peso float4 NOT NULL, sexo char(1) NOT NULL, pie_dominante char(3) NOT NULL, email varchar(100) NOT NULL, foto varchar(255) NOT NULL, estado char(1) NOT NULL, pais_id int2 NOT NULL, PRIMARY KEY (futbolista_id));
CREATE TABLE EVENTO (evento_id SERIAL NOT NULL, nombre varchar(20) NOT NULL, PRIMARY KEY (evento_id));
CREATE TABLE ESTADIO (estadio_id SERIAL NOT NULL, nombre_oficial varchar(50) NOT NULL, nombre_conocido varchar(25) NOT NULL, capacidad int4 NOT NULL, ubicacion varchar(255) NOT NULL, fecha_fundacion date NOT NULL, numero_tribunas int2 NOT NULL, dimensiones_campo varchar(50) NOT NULL, foto varchar(255) NOT NULL, equipo_id int4 NOT NULL, PRIMARY KEY (estadio_id));
CREATE TABLE CONTRATO (contrato_id SERIAL NOT NULL, fecha_inicio date NOT NULL, fecha_fin date NOT NULL, remuneracion_por_temporada float8 NOT NULL, descripcion varchar(255) NOT NULL, agente_id int2 NOT NULL, futbolista_id int4 NOT NULL, equipo_id int4 NOT NULL, tipo_contrato_id int2 NOT NULL, PRIMARY KEY (contrato_id));
CREATE TABLE AGENTE (agente_id SERIAL NOT NULL, nombre_completo varchar(50) NOT NULL, direccion varchar(255) NOT NULL, correo varchar(255) NOT NULL, foto varchar(255) NOT NULL, PRIMARY KEY (agente_id));
CREATE TABLE EQUIPO (equipo_id SERIAL NOT NULL, nombre_completo varchar(50) NOT NULL, nombre_corto varchar(15) NOT NULL, fecha_fundacion date NOT NULL, apodo varchar(15) NOT NULL, ubicacion date NOT NULL, numero_socios int2 NOT NULL, foto varchar(255) NOT NULL, PRIMARY KEY (equipo_id));
CREATE TABLE TIPO_CONTRATO (tipo_contrato_id SERIAL NOT NULL, descripcion varchar(25) NOT NULL, PRIMARY KEY (tipo_contrato_id));
CREATE TABLE CUERPO_TECNICO (cuerpo_tecnico_id SERIAL NOT NULL, nombre varchar(50) NOT NULL, PRIMARY KEY (cuerpo_tecnico_id));
CREATE TABLE PAIS (pais_id SERIAL NOT NULL, nombre varchar(25) NOT NULL, abreviatura char(3) NOT NULL, continente_id int4 NOT NULL, PRIMARY KEY (pais_id));
CREATE TABLE CONTINENTE (continente_id SERIAL NOT NULL, nombre varchar(15) NOT NULL, abreviatura char(3) NOT NULL, PRIMARY KEY (continente_id));
CREATE TABLE PARTIDO (partido_id SERIAL NOT NULL, hora time(6) NOT NULL, estadio_id int4 NOT NULL, jornada_id int4 NOT NULL, terna_arb_id int4 NOT NULL, PRIMARY KEY (partido_id));
CREATE TABLE FIXTURE (fixture_id SERIAL NOT NULL, descripcion varchar(20) NOT NULL, numero_equipos int2 NOT NULL, competencia_id int4 NOT NULL, PRIMARY KEY (fixture_id));
CREATE TABLE GRUPO (grupo_id SERIAL NOT NULL, nombre varchar(15) NOT NULL, abreviatura char(1) NOT NULL, PRIMARY KEY (grupo_id));
CREATE TABLE COMPETENCIA (competencia_id SERIAL NOT NULL, nombre varchar(50) NOT NULL, fecha_inicio date NOT NULL, fecha_fin date NOT NULL, PRIMARY KEY (competencia_id));
CREATE TABLE DETALLE_COMPETENCIA_PAIS (pais_id int2 NOT NULL, competencia_id int4 NOT NULL, PRIMARY KEY (pais_id, competencia_id));
CREATE TABLE TERNA (terna_id SERIAL NOT NULL, arbitro_id int4 NOT NULL, tipo_terna_id int4 NOT NULL, terna_arb_id int4 NOT NULL, PRIMARY KEY (terna_id));
CREATE TABLE JORNADA (jornada_id SERIAL NOT NULL, descripcion varchar(15) NOT NULL, fecha int4 NOT NULL, fixture_id int4 NOT NULL, grupo_id int4 NOT NULL, PRIMARY KEY (jornada_id));
CREATE TABLE INCIDENCIAS (incidencia_id SERIAL NOT NULL, futbolista_id int4 NOT NULL, evento_id int4 NOT NULL, minuto time(6) NOT NULL, detalle_incidencia varchar(25) NOT NULL, tipo char(5) NOT NULL, PRIMARY KEY (incidencia_id));
CREATE TABLE POSICION (posicion_id SERIAL NOT NULL, abreviatura char(3) NOT NULL, descripcion varchar(20) NOT NULL, PRIMARY KEY (posicion_id));
CREATE TABLE DETALLE_POSICION_FUTBOLISTA (futbolista_id int4 NOT NULL, posicion_id int4 NOT NULL, PRIMARY KEY (futbolista_id, posicion_id));
CREATE TABLE ALINEACION (alineacion_id SERIAL NOT NULL, descripcion varchar(10) NOT NULL, PRIMARY KEY (alineacion_id));
CREATE TABLE DETALLE_PARTIDO (equipo_id int4 NOT NULL, partido_id int4 NOT NULL, incidencia_id int4 NOT NULL, alineacion_id int4 NOT NULL, tipo char(1) NOT NULL, PRIMARY KEY (equipo_id, partido_id, incidencia_id, alineacion_id));
CREATE TABLE ARBITRO (arbitro_id SERIAL NOT NULL, arbitro_nombre varchar(50) NOT NULL, arbitro_estado char(1) NOT NULL, PRIMARY KEY (arbitro_id));
CREATE TABLE TIPO_TERNA (tipo_terna_id SERIAL NOT NULL, tipo_terna_nombre varchar(50) NOT NULL, tipo_terna_sigla varchar(5) NOT NULL, PRIMARY KEY (tipo_terna_id));
CREATE TABLE PROFESIONAL (profesional_id SERIAL NOT NULL, nombre varchar(50) NOT NULL, fecha_nacimiento date NOT NULL, estado bool NOT NULL, pais_id int2 NOT NULL, PRIMARY KEY (profesional_id));
CREATE TABLE DETALLE_CUERPO_TECNICO (cuerpo_tecnico_id int4 NOT NULL, profesional_id int4 NOT NULL, equipo_id int4 NOT NULL, PRIMARY KEY (cuerpo_tecnico_id, profesional_id, equipo_id));
CREATE TABLE TIPO_PROFESIONAL (tipo_profesional_id SERIAL NOT NULL, descripcion varchar(25) NOT NULL, abreviatura char(2) NOT NULL, PRIMARY KEY (tipo_profesional_id));
CREATE TABLE DETALLE_PROFESIONAL (profesional_id int4 NOT NULL, tipo_profesional_id int4 NOT NULL, PRIMARY KEY (profesional_id, tipo_profesional_id));
CREATE TABLE TERNA_ARBITRAL_2 (terna_arb_id SERIAL NOT NULL, terna_arb_nombre varchar(25) NOT NULL, terna_arb_estado char(1) NOT NULL, PRIMARY KEY (terna_arb_id));
ALTER TABLE CONTRATO ADD CONSTRAINT FKCONTRATO835160 FOREIGN KEY (agente_id) REFERENCES AGENTE (agente_id);
ALTER TABLE CONTRATO ADD CONSTRAINT FKCONTRATO905388 FOREIGN KEY (futbolista_id) REFERENCES FUTBOLISTA (futbolista_id);
ALTER TABLE CONTRATO ADD CONSTRAINT FKCONTRATO354447 FOREIGN KEY (equipo_id) REFERENCES EQUIPO (equipo_id);
ALTER TABLE CONTRATO ADD CONSTRAINT FKCONTRATO329589 FOREIGN KEY (tipo_contrato_id) REFERENCES TIPO_CONTRATO (tipo_contrato_id);
ALTER TABLE PAIS ADD CONSTRAINT FKPAIS356097 FOREIGN KEY (continente_id) REFERENCES CONTINENTE (continente_id);
ALTER TABLE PARTIDO ADD CONSTRAINT FKPARTIDO72646 FOREIGN KEY (estadio_id) REFERENCES ESTADIO (estadio_id);
ALTER TABLE FUTBOLISTA ADD CONSTRAINT FKFUTBOLISTA943560 FOREIGN KEY (pais_id) REFERENCES PAIS (pais_id);
ALTER TABLE DETALLE_COMPETENCIA_PAIS ADD CONSTRAINT FKDETALLE_CO763616 FOREIGN KEY (pais_id) REFERENCES PAIS (pais_id);
ALTER TABLE DETALLE_COMPETENCIA_PAIS ADD CONSTRAINT FKDETALLE_CO313081 FOREIGN KEY (competencia_id) REFERENCES COMPETENCIA (competencia_id);
ALTER TABLE FIXTURE ADD CONSTRAINT FKFIXTURE486174 FOREIGN KEY (competencia_id) REFERENCES COMPETENCIA (competencia_id);
ALTER TABLE JORNADA ADD CONSTRAINT FKJORNADA884481 FOREIGN KEY (fixture_id) REFERENCES FIXTURE (fixture_id);
ALTER TABLE PARTIDO ADD CONSTRAINT FKPARTIDO382402 FOREIGN KEY (jornada_id) REFERENCES JORNADA (jornada_id);
ALTER TABLE DETALLE_POSICION_FUTBOLISTA ADD CONSTRAINT FKDETALLE_PO847697 FOREIGN KEY (futbolista_id) REFERENCES FUTBOLISTA (futbolista_id);
ALTER TABLE DETALLE_POSICION_FUTBOLISTA ADD CONSTRAINT FKDETALLE_PO433633 FOREIGN KEY (posicion_id) REFERENCES POSICION (posicion_id);
ALTER TABLE INCIDENCIAS ADD CONSTRAINT FKINCIDENCIA764321 FOREIGN KEY (futbolista_id) REFERENCES FUTBOLISTA (futbolista_id);
ALTER TABLE INCIDENCIAS ADD CONSTRAINT FKINCIDENCIA767779 FOREIGN KEY (evento_id) REFERENCES EVENTO (evento_id);
ALTER TABLE DETALLE_PARTIDO ADD CONSTRAINT FKDETALLE_PA62399 FOREIGN KEY (equipo_id) REFERENCES EQUIPO (equipo_id);
ALTER TABLE DETALLE_PARTIDO ADD CONSTRAINT FKDETALLE_PA120127 FOREIGN KEY (partido_id) REFERENCES PARTIDO (partido_id);
ALTER TABLE DETALLE_PARTIDO ADD CONSTRAINT FKDETALLE_PA497738 FOREIGN KEY (alineacion_id) REFERENCES ALINEACION (alineacion_id);
ALTER TABLE TERNA ADD CONSTRAINT FKTERNA946704 FOREIGN KEY (arbitro_id) REFERENCES ARBITRO (arbitro_id);
ALTER TABLE TERNA ADD CONSTRAINT FKTERNA85047 FOREIGN KEY (tipo_terna_id) REFERENCES TIPO_TERNA (tipo_terna_id);
ALTER TABLE DETALLE_PROFESIONAL ADD CONSTRAINT FKDETALLE_PR877776 FOREIGN KEY (profesional_id) REFERENCES PROFESIONAL (profesional_id);
ALTER TABLE DETALLE_PROFESIONAL ADD CONSTRAINT FKDETALLE_PR520572 FOREIGN KEY (tipo_profesional_id) REFERENCES TIPO_PROFESIONAL (tipo_profesional_id);
ALTER TABLE DETALLE_CUERPO_TECNICO ADD CONSTRAINT FKDETALLE_CU343035 FOREIGN KEY (cuerpo_tecnico_id) REFERENCES CUERPO_TECNICO (cuerpo_tecnico_id);
ALTER TABLE DETALLE_CUERPO_TECNICO ADD CONSTRAINT FKDETALLE_CU284177 FOREIGN KEY (profesional_id) REFERENCES PROFESIONAL (profesional_id);
ALTER TABLE TERNA ADD CONSTRAINT FKTERNA269414 FOREIGN KEY (terna_arb_id) REFERENCES TERNA_ARBITRAL_2 (terna_arb_id);
ALTER TABLE PARTIDO ADD CONSTRAINT FKPARTIDO605400 FOREIGN KEY (terna_arb_id) REFERENCES TERNA_ARBITRAL_2 (terna_arb_id);
ALTER TABLE DETALLE_CUERPO_TECNICO ADD CONSTRAINT FKDETALLE_CU288977 FOREIGN KEY (equipo_id) REFERENCES EQUIPO (equipo_id);
ALTER TABLE JORNADA ADD CONSTRAINT FKJORNADA691598 FOREIGN KEY (grupo_id) REFERENCES GRUPO (grupo_id);
ALTER TABLE ESTADIO ADD CONSTRAINT FKESTADIO282320 FOREIGN KEY (equipo_id) REFERENCES EQUIPO (equipo_id);
ALTER TABLE DETALLE_PARTIDO ADD CONSTRAINT FKDETALLE_PA383066 FOREIGN KEY (incidencia_id) REFERENCES INCIDENCIAS (incidencia_id);
ALTER TABLE PROFESIONAL ADD CONSTRAINT FKPROFESIONA390165 FOREIGN KEY (pais_id) REFERENCES PAIS (pais_id);
